version: "3.8"

services:
  rag-tester-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-tester-3
    environment:
      - OPENAI_API_KEY=<OPENAI_API_KEY>
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py