version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SARVAM_API_KEY=${SARVAM_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    volumes:
      - .:/app
      - ./debug_audio:/app/debug_audio
    restart: unless-stopped
    
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      # Add your ngrok authentication token here
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:5000
    depends_on:
      - app
