name: Deploy indic-commerce to GCP Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/indic-commerce

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve \
        -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
        -var="service_account_id=${{ secrets.GCP_SA_ID }}" \
        -var="region=${{ secrets.GCP_REGION }}" \
        -var="image=${{ env.IMAGE_NAME }}" \
        -var="sarvam_api_key=${{ secrets.SARVAM_API_KEY }}" \
        -var="twilio_account_sid=${{ secrets.TWILIO_ACCOUNT_SID }}" \
        -var="twilio_auth_token=${{ secrets.TWILIO_AUTH_TOKEN }}" \
        -var="twilio_whatsapp_number=${{ secrets.TWILIO_WHATSAPP_NUMBER }}" \
        -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"
